apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:vHlR6jqSv09hlvgtZJCYvlcyuEkkt0p2z/GOcal/Wt7PL2wh2nRs/AB37t77/l24o1A6+2cRhFsMeFvpCpcLca2LQwgmz4DwwMt9ljYSLStE+8f7BawdWVU6VGEJa8GTc6KSprVGqLffW2qxOtBZDILGH7f7bScHX/wNzCX0mjz4Cj4hx/er7pniJLZHyKIv35DY0et8tIEsI1RqN0ckojTBARg6YFIqcOOOCLv4IenVxZeX6wpwI7Cik+CtGX++rpub6b8S4fgT7AaWlP5a4C2xiMO6c02GwQtMuix+k/2MniFAijYcjFLBbKA=,iv:gBzvmd+0m4ckBhaXNLyfUOEiGije6YK0Y9Tj27rJx6w=,tag:qyQYMgN46ZZT6jt26fNTlA==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - recipient: age1nlwnda9v3fmn06rltrm8lmk49fhyu6v0pge5j9t77uqtkfsqjpeq7elvkm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZNkRzdU1HRGU3SWREMEls
            N3pTZXB1VHp4azR1eTJZaE5YK3plTTVTWmpvCndkVHQ4dDdwbnJpeDZUcVRJMks3
            c2tpemZCREpZSnBndVdsWGIxY2xIRTgKLS0tIHdJcEJLdUhCcUtLSG5yT3Urb1JP
            SnRSTlB5VnF1M2NSK0NreHZtd0IyQkEKNJZ9uTTbOa/ZeSOCgL+WWnRcPxzCU7J/
            57iXLioCNTnS+XuTHtSKVPtZCcMe+wcfL5viL5tYNQ8QdYKZiy57Wg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-19T01:28:52Z"
    mac: ENC[AES256_GCM,data:HG5/0m3nJZliLX5OhovxgXubh5+8rdXJo2ndqQvXPq4pwkAUBCCaflaXcZTX9xTudGQqIYIB9ZvZLtbEhOyBVdppPpOTT2xA6P2OW6uLZrF+97wunpDVhZTHgaJ3+jvDJgTi7TxDkp7SHz7yvI8qRpwptcr7e7Q20uc2FdKA+Cw=,iv:EkotVnz5wIw4V9xKptWQNopKVYYipLaN+EQl/yA9e/w=,tag:RX055SQUum95TKmA3hatNQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
