apiVersion: v1
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:pXpK32GJdFACEB9NIMZCR/J2FsDT8B+sIWpJI38+9QyPBT/cGicen2ZbtIai99DPp5z26PNJ2bw=,iv:juhsjVhnW+OX21S/fCXoXy2w6wOLftmM1tijQy9msTw=,tag:LQJyRPJDDAaLU+58a7RsdA==,type:str]
kind: Secret
metadata:
    name: renovate-container-env
sops:
    age:
        - recipient: age1nlwnda9v3fmn06rltrm8lmk49fhyu6v0pge5j9t77uqtkfsqjpeq7elvkm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrUjU2V1c4Slg1NEZSMk1n
            Mkx0eXNld1oreThnR3d5b09pQWVsRFVUMTNnCnkvcW1YUk1mWHZ3YlFTeUQ1dDMw
            dFl5VTJxcVhrWUVUZG9xc1JGRmhsMXMKLS0tIDhtc1o4UWRsek9naVVzYnhnQm1z
            T2RTb1Y4eVhkK01nVU9CT2hsSnkvbW8KPC0rgSQiZg1IOnnr/LJv35AlCyLu1LUE
            DhninyRMIpbGSb9wqAR9SJCz8XCoIXQFdZtgd5weemIgadxhG2WsjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-19T18:53:33Z"
    mac: ENC[AES256_GCM,data:sXrm+Mtb+Y6wWkfViQyhij5gYgMh6521K6MmJZ8dIDRfYt4XEZCze475l6N31CMZMKh/XCX6lfvf0R5r6Hn+Qqru6VMEjPEiYng9OjLNc1lmvooFHdacD6nObnXQbMmKBj3Xe16zLOG+uro0pK4UXZwR4+ab7zCIVYiq59ElVLw=,iv:xkwUHshGOvschfrhsippHQY7NKiQDJZcUwOQZHdZk2Q=,tag:t5fAAUIGHvVDeOroKxpsNA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
